# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mealprep-nlp
  name: mealprep-nlp
  namespace: default
spec:
  ports:
  - nodePort: 30024
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: mealprep-nlp
  type: NodePort

---

# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: v1
    run: mealprep-nlp
  name: mealprep-nlp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mealprep-nlp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: mealprep-nlp
    spec:
      containers:
      - name: mealprep-nlp
        image: mealprep-nlp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        command: ["python","./run.py"]
