"""Remove tester 3

Revision ID: 22b69b64d241
Revises: 2f56110cc8bc
Create Date: 2018-04-27 18:16:41.926903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b69b64d241'
down_revision = '2f56110cc8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'tester3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('tester3', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
