"""Add tester2

Revision ID: 22f393c6f8d6
Revises: 8fc8fad46bcb
Create Date: 2018-04-27 18:15:15.646718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f393c6f8d6'
down_revision = '8fc8fad46bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('tester2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'tester2')
    # ### end Alembic commands ###
