"""Add tester 3

Revision ID: 2f56110cc8bc
Revises: 5ebdca9d64f3
Create Date: 2018-04-27 18:16:34.243103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f56110cc8bc'
down_revision = '5ebdca9d64f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('tester3', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'tester3')
    # ### end Alembic commands ###
