"""Add tester3, remove others

Revision ID: 5ebdca9d64f3
Revises: 22f393c6f8d6
Create Date: 2018-04-27 18:16:13.728672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebdca9d64f3'
down_revision = '22f393c6f8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'tester2')
    op.drop_column('profile', 'tester1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('tester1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('profile', sa.Column('tester2', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
