"""empty message

Revision ID: 7fb050831deb
Revises: 56604aef5fb1
Create Date: 2018-04-27 17:13:48.865030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb050831deb'
down_revision = '56604aef5fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('email', sa.String(length=120), nullable=False))
    op.alter_column('profile', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('profile', 'brand_new')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('brand_new', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.alter_column('profile', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('profile', 'email')
    # ### end Alembic commands ###
